### ISSUE TITLE
4.12.5 EFI kernel does hangs at boot

### ISSUE THREAD

**Issue by Azimoth** [sakaki-/buildkernel#16] opened 2017-08-15 13:15 UTC
I installed Gentoo on my laptop following your guide (great work!) and ever since used genup/buildkernel for kernel updates. This worked fine for kernel version < 4.10.

Every version newer than that hangs at boot. The screen just stays blank where the EFI kernel used to take over and I don't see any output nor a password prompt to decrypt the hard drive.

At that point I decided to wait for the stable update and hoped for this problem to be fixed by then.
Unfortunately it isn't.

Are you aware of anything that changed with kernel 4.10? A new option set (or not set) by default that renders my kernel unbootable?
Do I have to change something in the config files manually? I don't even know where to look for information on this problem, since I don't have any dmesg output or something similar.

My kernel .config looks [like this](https://paste.pound-python.org/show/wqheVjTHZN5MdIDv836y/).

Thanks a lot for your work anyways! ;)

**Comment by sakaki-** [comment] 2017-08-15 14:59
Hi, sorry to hear you are having problems with this. I'm not aware of any kernel changes that would cause your issue specifically - I'm writing this on a laptop booted with `4.11.3-gentoo`, `buildkernel` and `plymouth` splash, and my main desktop uses a text boot with `4.12.5-gentoo` atm.
 
Does the kernel even start at all? What may be happening is that the EFI boot list has got corrupted in your machine's BIOS somehow. Try going onto your boot USB key and copying (if you have space) `/EFI/Boot/gentoo.efi` to `/EFI/Boot/bootx64.efi`. You can then try selecting this device (i.e. the USB key) directly as a boot target from your BIOS. If this works, then the issue is with the EFI boot list (which will need cleaning).

Please let me know how you get on!

**Comment by Azimoth** [comment] 2017-08-15 16:12
Thank you for your quick reply.

I did not expect you to have time to help me troubleshooting my problem, so I did not go into detail too much.

First of all, my system is a Macbook Pro 8,1 (early 2011) with a Sandy Bridge CPU, so there's not BIOS (I think).
How it used to work so far looks like this:
As usual on a Mac the screen turns white after the start chime.
If it was a pure Apple system the apple logo would appear now, but since I'm using a EFI stub kernel, the screen remains white for about 13-14 seconds until text output starts to fly by, eventually resulting in a password request to decrypt the hard drive. (By default with plymouth)

But instead, the screen simply remains white forever (well, I never waited longer than 2-3 minutes).
I tried moving gentoo.efi to bootx64.efi, but this did not make a difference.
After removing the newly compiled kernel and removing the ".old" ending from the backup files of the old kernel everything boots up again as before. Is this a proof that the EFI boot list is still intact?

**Comment by sakaki-** [comment] 2017-08-15 16:29
That certainly suggests a problem with the new kernel, or its configuration, or possibly plymouth/buildkernel/genkernel-next.

What version is the last known good kernel that does boot? (and yes, if it the renamed old kernel works, then your EFI boot list is OK, so we can rule that out as a problem)

If you do a `diff` between the old (last-known-good) kernel's .config and your new (non-booting) kernel's .config (the one you posted), what do you get? Sometimes the `make olddefconfig` step can introduce something strange, though that is unlikely.

You could try pulling in an old `gentoo-sources` version temporarily (say 4.9.41), then use `buildkernel` to build it (when in a system booted from your last-known-good kernel), and see if you can boot with that. That would help eliminate (the current versions of) plymouth, buildkernel or genkernel-next as being the cause of the issue. Then we would just be left with the kernel and its config to look at. Worst case you could then bisect to find find the kernel commit that was causing the issue.

Pls let me know how it goes.

**Comment by Azimoth** [comment] 2017-08-15 18:00
The latest ~ kernel available according to eix was 4.9.43, so I compiled that one and it works, hence this is the last-known-good kernel.

This is the [output of diff](https://paste.pound-python.org/show/w0Ncqs7e2bPEz1S7BVM3/)  (4.9.43 vs. 4.12.5 .config)

I cannot tell which of the lines matter and which don't...

So, plymouth, buildkernel or genkernel-next are not the culprits as well?

**Comment by sakaki-** [comment] 2017-08-15 18:30
> So, plymouth, buildkernel and genkernel-next are not the culprits as well?

It looks that way, yes. So, narrowed down to the kernel and / or its configuration.
Do you know which was the first (i.e., earliest, lowest) kernel version that *failed* to boot for you?

**Comment by sakaki-** [comment] 2017-08-15 18:40
OK good, that's a narrower range to work with.

Would you mind diffing the 4.9.43 (LNG) with 4.10.2 (presumably non-booting) .config please?

**Comment by Azimoth** [comment] 2017-08-15 18:41
Sure, [here we go](https://paste.pound-python.org/show/MCYvzg4J0E8Yl56YeGyz/)

**Comment by sakaki-** [comment] 2017-08-15 19:05
Most of that looks fairly harmless, but there are a few things that look odd. For example:

```
3c3
< # Linux/x86 4.9.43-gentoo Kernel Configuration
---
> # Linux/x86 4.10.2-gentoo Kernel Configuration
--- snip ---
616c627
< CONFIG_PM_STD_PARTITION="/dev/mapper/vg1-swap"
---
> CONFIG_PM_STD_PARTITION=""
```

how did `make olddefconfig` end up doing that? It should preserve information. Then, looking at the config you posted in your first message (the 4.12.5 one), it has:
```
CONFIG_PM_STD_PARTITION="/dev/mapper/vg1-swap"
```
again.

There are no 4.10 kernels in the Gentoo tree at the moment. However, the Gentoo specific patches are not really that important, so the next thing is to try fetching a kernel.org version and try building that. Fetch it from https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.10.2.tar.xz.  Then untar it, move into `/usr/src/`, fix up your `/usr/src/linux` link to point to it, `cd /usr/src/linux` and then run `buildkernel`. It should use your LNG kernel's config as a basis. When complete, do a diff of the configs, and compare it to the one you just posted. Are they the same? Try booting with this (vanilla 4.10.2) kernel. Any change this time?

**Comment by Azimoth** [comment] 2017-08-15 19:10
Well, regarding the question "why is it gone earlier and returns later on": I never used any kernel >=4.10 so the 4.12.5 .config is based on the 4.9.43 .config, where the information was present all the time.

As for the rest... I will need some time to do that, but I'll let you know about the progress!

**Comment by sakaki-** [comment] 2017-08-15 19:22
OK thanks. This is going to be a bit of a pain, but it should deterministically get an answer:

- If vanilla (kernel.org) 4.10.2 fails to boot, download the kernel.org 4.9.43 (equivalent of your LNG) and try building & booting that. If successful that will establish that there is nothing in the Gentoo patchset at issue. We can then work with the vanilla tree, which is easier.
- Then, you could try the 4.10.1 and 4.10 (no .0 suffix), to hopefully tighten the range further.
Once you have single increment good/failing candidates, we can try a kernel bisect if necessary (a binary chop to find the offending commit) - if the .config diff doesn't throw up anything obvious.

We'll pick it up again once you have the results of the above.  Good luck!

**Comment by Azimoth** [comment] 2017-08-15 20:46
The vanilla kernel is compiled and it does not boot... here is the diff of [gentoo-4.10.2 and vanilla-4.10.2](https://paste.pound-python.org/show/0DK9Kvs1eoQlLsrE1tdI/).
I'll compile the vanilla 4.9.43 kernel next (I don't know whether I'll finish this today...).

**Comment by Azimoth** [comment] 2017-08-16 06:31
The vanilla kernel of 4.9.43 does boot (just like the Gentoo kernel). The diff in .configs is really short:

3c3
< # Linux/x86 4.9.43 Kernel Configuration
---
> # Linux/x86 4.9.43-gentoo Kernel Configuration
4a5,17
> 
> #
> # Gentoo Linux
> #
> CONFIG_GENTOO_LINUX=y
> CONFIG_GENTOO_LINUX_UDEV=y
> CONFIG_GENTOO_LINUX_PORTAGE=y
> 
> #
> # Support for init systems, system and service managers
> #
> CONFIG_GENTOO_LINUX_INIT_SCRIPT=y
> CONFIG_GENTOO_LINUX_INIT_SYSTEMD=y
3287a3301
> # CONFIG_FB_CON_DECOR is not set

So I'm going to try 4.10 vanilla next then...

**Comment by Azimoth** [comment] 2017-08-16 08:01
The vanilla 4.10 kernel did not boot either, so apparently we have minimized the version range.
These are the diffs for [vanilla 4.9.43 and vanilla 4.10](https://paste.pound-python.org/show/OxwMOml1lohy3lLlobC3/).

Does it throw up anything obvious?

**Comment by sakaki-** [comment] 2017-08-16 10:19
Most of them look harmless, but there are a few (e.g. `> CONFIG_APPLE_PROPERTIES=y`) that might possibly have an impact.

Before proceeding to a full bisect, it's probably worth building another 4.10 in which you turn **off** all the new config features (so where the above diff shows an entry as having been inserted and turned on (=y), turn it off; leave everything else in the config as is). Does that version boot?

**Comment by Azimoth** [comment] 2017-08-16 13:23
So, I'm writing this post using a vanilla 4.10(.0) kernel. :)
Here's the corresponding [kernel .config](https://paste.pound-python.org/show/sav1aGVFOQy3RER0Mgsp/)
and here's the diff between the [LNG vanilla 4.9.43 kernel and the newly working vanilla 4.10 kernel](https://paste.pound-python.org/show/5pMJxZace4jxe3XfiDir/)

how can we narrow down any further, where the problem was/is?

**Comment by sakaki-** [comment] 2017-08-16 19:29
Yay! good result. The next thing is yes, go back to a 4.9.34 kernel, and generate a non-working 4.10 config again. Then inhibit things until you get a working kernel. One thing - I think that  `CONFIG_INITRAMFS_COMPRESSION_NONE=y` should **not** be unset (although you can easily verify this).

As to finding the problematic item, you could actually binary chop the search. Start with the 4.9.34-based non-working 4.10 config. Then comment out the first 1/2 of the new =y stuff. If that boots, do the same, but with only the first 1/4 commented out; if it does not boot, verify that it will boot with the second half commented out. Then iterate with the narrower search, until you end up with a single entry.
As you say, you won't be able to turn off everything, since some will be forced as the result of other items, but what you can probably write a little script to process the config based on an input file with the list of keys to comment out.
Shouldn't take long to get to the answer! Good luck.

**Comment by Azimoth** [comment] 2017-08-17 10:49
Computers work in mysterious ways, occasionally. The problem has vanished and no matter what option I re-activate: It stays gone.

BUT I have a theory.

While waiting for the kernel to compile I wanted to know more about initramfs compression.
I found [this post describing a patch](https://patchwork.kernel.org/patch/9738825/). In short:

> Commit db2aa7fd15e857891cefbada8348c8d938c7a2bc ("initramfs: allow again
> choice of the embedded initram compression algorithm") is problematic
> because CONFIG_INITRAMFS_COMPRESSION which is used to determine the
> initramfs_data.cpio extension/compression is a string, and due to how
> Kconfig works it will evaluate in order, how to assign it.
> 
> Setting CONFIG_INITRAMFS_COMPRESSION_NONE with
> CONFIG_INITRAMFS_SOURCE="" cannot possibly work (because of the depends
> on INITRAMFS_SOURCE!="" imposed on CONFIG_INITRAMFS_COMPRESSION ) yet we
> still get CONFIG_INITRAMFS_COMPRESSION assigned to ".gz" because
> CONFIG_RD_GZIP=y is set in my kernel, even when there is no initramfs
> being built.

Looking at the old 4.9.34 .config in line 214 it says 
CONFIG_INITRAMFS_COMPRESSION=""

And looking at the diff between the old 4.9.34 and non-working 4.12.5 .configs it says in line 26
CONFIG_INITRAMFS_COMPRESSION=""
as still being present in the 4.12.5 .config file (and it was also present in the non-working 4.10.2 kernel).

Now this line is nowhere to be found in the .config file anymore. 
Instead it says 
```
# CONFIG_INITRAMFS_COMPRESSION_NONE is not set
CONFIG_INITRAMFS_COMPRESSION_XZ=y
CONFIG_INITRAMFS_COMPRESSION=".xz"
```
and the second line turns to 
`# CONFIG_INITRAMFS_COMPRESSION_XZ is not set`
when I set
`Built-in initramfs compression mode (None)`
and I am prompted for "y/n/?" input during compilation.

So the remaining question is: Do I want to compress my initramfs (so it loads faster but the CPU has to decompress it?) or is my SSD faster anyway, the a uncompressed kernel loads quicker anyways?

**Comment by sakaki-** [comment] 2017-08-17 11:19
You need not compress it - it is transcluded inside the kernel when booting under EFI, and the whole kernel image is _itself_ compressed.

In fact, it used to be the case that only uncompressed initramfs would work, when building into the kernel in this fashion. That may since have changed.

On 17 August 2017 11:49:01 BST, Azimoth <notifications@github.com> wrote:
>Computers work in mysterious ways, occasionally. The problem has
>vanished and no matter what option I re-activate: It stays gone.
>
>BUT I have a theory.
>
>While waiting for the kernel to compile I wanted to know more about
>initramfs compression.
>I found [this post describing a
>patch](https://patchwork.kernel.org/patch/9738825/). In short:
>
>> Commit db2aa7fd15e857891cefbada8348c8d938c7a2bc ("initramfs: allow
>again
>> choice of the embedded initram compression algorithm") is problematic
>> because CONFIG_INITRAMFS_COMPRESSION which is used to determine the
>> initramfs_data.cpio extension/compression is a string, and due to how
>> Kconfig works it will evaluate in order, how to assign it.
>> 
>> Setting CONFIG_INITRAMFS_COMPRESSION_NONE with
>> CONFIG_INITRAMFS_SOURCE="" cannot possibly work (because of the
>depends
>> on INITRAMFS_SOURCE!="" imposed on CONFIG_INITRAMFS_COMPRESSION ) yet
>we
>> still get CONFIG_INITRAMFS_COMPRESSION assigned to ".gz" because
>> CONFIG_RD_GZIP=y is set in my kernel, even when there is no initramfs
>> being built.
>
>Looking at the old 4.9.34 .config in line 214 it says 
>CONFIG_INITRAMFS_COMPRESSION=""
>
>And looking at the diff between the old 4.9.34 and non-working 4.12.5
>.configs it says in line 26
>CONFIG_INITRAMFS_COMPRESSION=""
>as still being present in the 4.12.5 .config file (and it was also
>present in the non-working 4.10.2 kernel).
>
>Now this line is nowhere to be found in the .config file anymore. 
>Instead it says 
>```
># CONFIG_INITRAMFS_COMPRESSION_NONE is not set
>CONFIG_INITRAMFS_COMPRESSION_XZ=y
>CONFIG_INITRAMFS_COMPRESSION=".xz"
>```
>and the second line turns to 
>`# CONFIG_INITRAMFS_COMPRESSION_XZ is not set`
>when I set
>`Built-in initramfs compression mode (None)`
>and I am prompted for "y/n/?" input during compilation.
>
>So the remaining question is: Do I want to compress my initramfs (so it
>loads faster but the CPU has to decompress it?) or is my SSD faster
>anyway, the a uncompressed kernel loads quicker anyways?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/sakaki-/buildkernel/issues/16#issuecomment-323035247

-- 
sakaki@deciban.com

**Comment by Azimoth** [comment] 2017-08-17 17:38
I was rather inadvertendly able to narrow it down to this diff:

> 212,214c212,214
> < # CONFIG_INITRAMFS_COMPRESSION_NONE is not set
> < CONFIG_INITRAMFS_COMPRESSION_XZ=y
> < CONFIG_INITRAMFS_COMPRESSION=".xz"
> ---
> > CONFIG_INITRAMFS_COMPRESSION_NONE=y
> > # CONFIG_INITRAMFS_COMPRESSION_XZ is not set
> > CONFIG_INITRAMFS_COMPRESSION=""

The upper .config is a working kernel, the lower is the one that hangs at boot.
That riddle is solved then... (well, not solved, but the problem is fixed^^)

I thank you VERY much for 
- your guide, without which I probably would not have made it through the installation on my Macbook ( the official Handbook is less comprehensive for that special case)
- your awesome tools and repositories!
- the time you spent guiding me through this process. Now I definitely feel prepared for the next time when a kernel won't boot. ;)

**Comment by sakaki-** [comment] 2017-08-17 18:35
No problem, glad you got it to work in the end!

It's a little odd that that was the source; on my desktop for example I have:
```console
~ # zgrep INITRAMFS /proc/config.gz 
CONFIG_INITRAMFS_SOURCE="/boot/initramfs.cpio"
CONFIG_INITRAMFS_ROOT_UID=0
CONFIG_INITRAMFS_ROOT_GID=0
CONFIG_INITRAMFS_COMPRESSION_NONE=y
# CONFIG_INITRAMFS_COMPRESSION_GZIP is not set
# CONFIG_INITRAMFS_COMPRESSION_BZIP2 is not set
# CONFIG_INITRAMFS_COMPRESSION_LZMA is not set
# CONFIG_INITRAMFS_COMPRESSION_XZ is not set
# CONFIG_INITRAMFS_COMPRESSION_LZO is not set
# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set
CONFIG_INITRAMFS_COMPRESSION=""
~ # uname -r
4.12.3-gentoo
```
Which if I understand it correctly are the settings that have caused you trouble. But, if it works it works ^-^.

You could try using your new (minimally modified) .config as the basis for a more modern kernel (4.12.x) and check that that boots also (with xz on) and then, once booted, use menuconfig to turn the xz initramfs compression off, and see if the resulting 4.12.x fails to boot. It may be a kconfig autoupdate rule has gone awry somewhere.

Then, one last thing that would be worth doing - you mentioned above you had opened a thread on the Gentoo forums about this issue. In case anyone else has found themselves with the same problem, it'd be good to mark it '[solved]' and add a short note describing what you found out regarding the initramfs settings.

**Comment by Azimoth** [comment] 2017-08-18 06:21
Apparently `make olddefconfig` doesn't like my configuration either:
`.config:5962:warning: override: reassigning to symbol INITRAMFS_COMPRESSION_NONE`

which leads to [this behaviour](https://paste.pound-python.org/show/1veS0k4gvAPRIcWfv07p/).
Even without touching anything, my .config file is changed into a non-booting version, unless I manually select `CONFIG_INITRAMFS_COMPRESSION=".xz"` and save the kernel configuration...

**Comment by sakaki-** [comment] 2017-08-18 08:46
OK, but if you set `CONFIG_INITRAMFS_COMPRESSION=".xz"` you can get a booting 4.12.5?
If so, what happens if you try then switching the compression off, via `make menuconfig` / `buildkernel -m` (not via an edit and `make olddefconfig`). Does that work?

**Comment by Azimoth** [comment] 2017-08-22 06:43
Hi, I'm sorry it took me a while to get back to you!
You mean manually deselecting all "Support initial ramdisks compressed using * " and setting/keeping "Built-in initramfs compression mode (None)"?

I tried a kernel with that configuration and it was not booting...

**Comment by sakaki-** [comment] 2017-08-22 10:00
It's possible I guess that:

- xz and other compressed integral initramfs are now OK to use, and
- the size of the (pre-application-of-the-outer-compression) kernel is too large (on your platform) without xz (or similar).

If that's the case, then you'll need to turn off `buildkernel's` default (which is to activate `INITRAMFS_COMPRESSION_NONE`). To do this, edit `/etc/buildkernel.conf`, uncomment the `user_conform_config_file()` function, and set it to something like:
```bash
user_conform_config_file() {
    unset_kernel_config "INITRAMFS_COMPRESSION_NONE"
    set_kernel_config "INITRAMFS_COMPRESSION_XZ" "y"
    set_kernel_config "INITRAMFS_COMPRESSION=" ".xz"
}
```

**Comment by sakaki-** [comment] 2017-11-03 11:16
I assume this is working now - closing. Feel free to re-open if required.

**Closed by sakaki-** 2017-11-03 11:16 UTC

**Comment by sineer** [comment] 2018-04-08 18:30
I googled and saw this issue by luck and it turns out that is the fix to my black screen gentoo efi boot... The uncompressed initramfs is too big and the system wouldn't even display an error just black screen and reboot after ~10sec... Compressing using XZ as you documented above fixed that.

**Comment by sakaki-** [comment] 2018-04-08 19:09
Hmm - I might just make xz compression the default in `buildkernel` in that case, as this issue may be affecting others.

**Comment by sineer** [comment] 2018-04-08 20:38
Hi friend, thank you very much for your awesome guide btw, it got me started on gentoo and setup just the way I wanted 👍 

Another heads up perhaps for recent kernel (I'm using 4.15) with default config I had to add two crypto option to my kernel for it to decrypt keyfile:  XTS and ECB. 

this link describes the problem I had: https://github.com/voidlinux/void-packages/issues/5871
